<?php
define('LABORATORYPIC','http://adude.in/cpl/laboratoryprofile');
define('DOCTORPIC','http://adude.in/cpl/doctorprofile');
define('BLOODBANKPIC','http://adude.in/cpl/bloodbankprofile');
define('DIAGNOSTICPIC','http://adude.in/cpl/diagnosticprofile');
define('HOSPITALPIC','http://adude.in/cpl/hospitalprofile');
define('STOREPIC','http://adude.in/cpl/storeprofile');
define('SLIDERS','http://adude.in/cpl/sliders');
define('WORKICON','http://adude.in/cpl/workicons');
define('DOCCATICON','http://adude.in/cpl/doctorcategory');
define('BANNER','http://adude.in/cpl/banner');
define('WELCOME','http://adude.in/cpl/welcomepics');
define('PRODUCTCATEGORY','http://adude.in/cpl/productcategory');
define('PRODUCTIMAGES','http://adude.in/cpl/productimages');
define('HOSPITALTYPE','http://adude.in/cpl/hospitaltype');
define('HOSPITALDOCTOR','http://adude.in/cpl/hospitaldoctor');
?>